# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b66f2dce17c90ede1a744f48a2d5229d8f43ccb7ff26d2c5d7feabfe98ba11ecd0e38ee2a06d933690b68de46954369e5434e15e7e5cdd74380142ee86d7fc7

test:
  secret_key_base: dd6d24a7689a6a3e7e42c5b467d608e9354fc535194d3b6cbfcb065cf8c7895fff65efc50a1bc498538c4579f9227888eed187a6ef391afcb698e31d264472e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
